### ISSUE TITLE
关于周期定时任务的处理

### ISSUE THREAD

**Issue by pigwantacat** [antlabs/timer#18]
当我创建定时器，再去创建周期性定时任务，最后调用run方法，在此创建周期性定时任务前后这段时间如果有休眠，它都会有执行结果，这是正常的吗
在创建周期性定时任务前休眠
![image](https://github.com/antlabs/timer/assets/79680042/475e588c-31e5-4e14-be4f-b0cbcecb1a6d)
在创建周期性定时任务后休眠
![image](https://github.com/antlabs/timer/assets/79680042/b31ec550-08a4-461a-8c35-002684fd4801)

**Comment by guonaihong** [comment]
<img width="591" alt="image" src="https://github.com/antlabs/timer/assets/5006959/f810a0c0-6e91-4332-8f5d-ac4dca2e2fbd">
我这边ok。你的问题看起来是go test的缓存导致的。在终端里面用
```cmd
go -test -test.run="函数和名" -v -count=1
``` 试下

**Comment by pigwantacat** [comment]
```go
# 这样可以
tm := timer.NewTimer(timer.WithMinHeap())
# 这样就不行
tm := timer.NewTimer()
```
![image](https://github.com/antlabs/timer/assets/79680042/e639c97c-73ea-498a-8542-41a531d7fda4)
![image](https://github.com/antlabs/timer/assets/79680042/ea01a43a-b95a-4dc2-95dd-84be3b3098cd)

**Comment by guonaihong** [comment]
感谢，我看下。

**Comment by guonaihong** [comment]
@pigwantacat 使用v0.0.12版本.
