### ISSUE TITLE
最小堆定时器cpu占用太高

### ISSUE THREAD

**Issue by destinyzhang** [antlabs/timer#25]
win 和linux 都是 95以上的cpu 
换成时间轮就降下去了

**Comment by guonaihong** [comment]
有可以复现的代码吗？我分析下。

**Comment by destinyzhang** [comment]
package main

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	atimer "github.com/antlabs/timer"
	"github.com/gin-gonic/gin"
)

func RunSafe(fn func()) {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println("err!=nil", err)
		}
	}()
	fn()
}

func GoSafe(fn func()) {
	go RunSafe(fn)
}

var tm atimer.Timer = nil

func init() {
	StartTimer()
	ScheduleFunc(time.Hour*24, func() {
		GoSafe(func() {
			fmt.Println("schedule func test")
		})
	})

	ScheduleFunc(time.Hour*12, func() {
		GoSafe(func() {
			fmt.Println("schedule func test")
		})
	})
}

func StartTimer() {
	if tm != nil {
		return
	}
	tm = atimer.NewTimer(atimer.WithMinHeap()) //最小堆cpu 很高
	// tm = atimer.NewTimer() //时间轮正常
	GoSafe(func() {
		tm.Run()
	})
}

func AddTimerAfterFunc(expire time.Duration, callback func()) {
	tm.AfterFunc(expire, callback)
}

func ScheduleFunc(expire time.Duration, callback func()) {
	tm.ScheduleFunc(expire, callback)
}

func StopTimer() {
	tm.Stop()
}

func CatchSignals(cb func()) {
	sigs := make(chan os.Signal, 1)
	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		sig := <-sigs
		fmt.Println()
		fmt.Println(sig)
		if cb != nil {
			cb()
		}
	}()
}

var server *http.Server

func Startserver() {
	gin.SetMode(gin.ReleaseMode)
	router := gin.Default()
	server = &http.Server{
		Addr:    "127.0.0.1:8080",
		Handler: router,
	}
	StartTimer()
	defer StopTimer()
	if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		fmt.Println("server listen err: ", err)
	}
	fmt.Println("server shutdown!!")
}

func main() {
	CatchSignals(GracefulShutDown)
	Startserver()
}

func GracefulShutDown() {
	fmt.Println("server shutdown start!!")
	server.Shutdown(context.Background())
}
测试代码

**Comment by guonaihong** [comment]
收到。

**Comment by guonaihong** [comment]
跑多久会出现cpu过高的现象？把上面代码的时间改成1s，一个小时之后还是很低。
必现的条件是？

**Comment by destinyzhang** [comment]
![lnx](https://github.com/antlabs/timer/assets/12708818/8bdda779-4ef6-4f65-bae6-6a8468533443)
![win](https://github.com/antlabs/timer/assets/12708818/2c767112-c36f-4ef2-b8fb-a6e334a385ce)
不用修改任何代码 这是在win10和centos上的cpu占用率 华为云上也是一样的效果

**Comment by destinyzhang** [comment]
![heap](https://github.com/antlabs/timer/assets/12708818/edc4f888-b04f-4587-bd30-72051d346b29)
![wheel](https://github.com/antlabs/timer/assets/12708818/5108ccbd-df05-49c8-9342-f9c51d28f35c)
[cpu_heap.cpuprofile](https://github.com/antlabs/timer/files/15315547/cpu_heap.cpuprofile)
[cpu_wheel.cpuprofile](https://github.com/antlabs/timer/files/15315548/cpu_wheel.cpuprofile)

**Comment by guonaihong** [comment]
感谢。

**Comment by guonaihong** [comment]
用下最新的commit(c35e2416f43ca0b1aff4c72bee7bab0322c19497)，看下有无问题，我这边测试下好了。

**Comment by destinyzhang** [comment]
正常了 谢谢

**Comment by guonaihong** [comment]
🤝 ，感谢提供的复现代码。那这个问题先关闭了，有问题可以随时打开。
