### ISSUE TITLE
不支持多线程么？会崩溃

### ISSUE THREAD

**Issue by ethsonliu** [antlabs/timer#3]
```golang
// thread 1
downloadTimer = timer.NewTimer()
go downloadTimer.Run()

// thread 2
downloadTimer.ScheduleFunc(downloadTimeDuration, func() {
		DownloadTimeoutReset()
	})
}
```

当 thread 2 运行的时候，报错如下，

```
2021/03/01 03:00:55 http: panic serving 192.168.201.14:52505: runtime error: invalid memory address or nil pointer dereference
goroutine 27 [running]:
net/http.(*conn).serve.func1(0x14c8480)
        D:/Go/src/net/http/server.go:1772 +0xf0
panic(0x377188, 0x685b70)
        D:/Go/src/runtime/panic.go:975 +0x3d4
runtime/internal/atomic.goLoad64(0x150139c, 0x1501360, 0x1480000)
        D:/Go/src/runtime/internal/atomic/atomic_arm.go:131 +0x1c
github.com/antlabs/timer.(*Time).lockPushBack(0x1501360, 0x14505c0, 0x2, 0x0, 0x5, 0x0)
        D:/GOPATH/pkg/mod/github.com/antlabs/timer@v0.0.5/time_wheel_node.go:51 +0xe8
github.com/antlabs/timer.(*timeWheel).add(0x14fa000, 0x14505c0, 0x40b, 0x0, 0x12c)
        D:/GOPATH/pkg/mod/github.com/antlabs/timer@v0.0.5/time_wheel.go:123 +0x1f4
github.com/antlabs/timer.(*timeWheel).ScheduleFunc(0x14fa000, 0xb2d05e00, 0x0, 0x3d380c, 0x14007e0, 0x320464)
        D:/GOPATH/pkg/mod/github.com/antlabs/timer@v0.0.5/time_wheel.go:159 +0xf0
main.ResetTimer()
        E:/Project/go_update/src/handler.go:257 +0x4c
main.FirmwareUpdateHandler(0x446e08, 0x16121b0, 0x15fe080)
        E:/Project/go_update/src/handler.go:721 +0xd5c
net/http.HandlerFunc.ServeHTTP(0x3d37f8, 0x446e08, 0x16121b0, 0x15fe080)
        D:/Go/src/net/http/server.go:2012 +0x34
net/http.(*ServeMux).ServeHTTP(0x68c470, 0x446e08, 0x16121b0, 0x15fe080)
        D:/Go/src/net/http/server.go:2387 +0x16c
net/http.serverHandler.ServeHTTP(0x14ae630, 0x446e08, 0x16121b0, 0x15fe080)
        D:/Go/src/net/http/server.go:2807 +0x88
net/http.(*conn).serve(0x14c8480, 0x447568, 0x1604020)
        D:/Go/src/net/http/server.go:1895 +0x7d4
created by net/http.(*Server).Serve
        D:/Go/src/net/http/server.go:2933 +0x2d0
```

当我把 thread 2 的 ScheduleFunc 注释掉就正常了，看了下源码实现，是用的 lockPushBack，应该没问题啊，大大的疑问。

**Comment by guonaihong** [comment]
一开始给event库设计的，理想是单线程的场景。现在只能外层加把锁。后面把timer设计成无锁数据结构。这样就不需要保护了。



---原始邮件---
发件人: "Ethson Liu"<notifications@github.com&gt;
发送时间: 2021年3月1日(周一) 中午11:02
收件人: "antlabs/timer"<timer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [antlabs/timer] 不支持多线程么？会崩溃 (#3)




 // thread 1 downloadTimer = timer.NewTimer() go downloadTimer.Run() // thread 2 downloadTimer.ScheduleFunc(downloadTimeDuration, func() { DownloadTimeoutReset() }) }
 
当 thread 2 运行的时候，报错如下，
 2021/03/01 03:00:55 http: panic serving 192.168.201.14:52505: runtime error: invalid memory address or nil pointer dereference goroutine 27 [running]: net/http.(*conn).serve.func1(0x14c8480)         D:/Go/src/net/http/server.go:1772 +0xf0 panic(0x377188, 0x685b70)         D:/Go/src/runtime/panic.go:975 +0x3d4 runtime/internal/atomic.goLoad64(0x150139c, 0x1501360, 0x1480000)         D:/Go/src/runtime/internal/atomic/atomic_arm.go:131 +0x1c github.com/antlabs/timer.(*Time).lockPushBack(0x1501360, 0x14505c0, 0x2, 0x0, 0x5, 0x0)         D:/GOPATH/pkg/mod/github.com/antlabs/timer@v0.0.5/time_wheel_node.go:51 +0xe8 github.com/antlabs/timer.(*timeWheel).add(0x14fa000, 0x14505c0, 0x40b, 0x0, 0x12c)         D:/GOPATH/pkg/mod/github.com/antlabs/timer@v0.0.5/time_wheel.go:123 +0x1f4 github.com/antlabs/timer.(*timeWheel).ScheduleFunc(0x14fa000, 0xb2d05e00, 0x0, 0x3d380c, 0x14007e0, 0x320464)         D:/GOPATH/pkg/mod/github.com/antlabs/timer@v0.0.5/time_wheel.go:159 +0xf0 main.ResetTimer()         E:/Project/go_update/src/handler.go:257 +0x4c main.FirmwareUpdateHandler(0x446e08, 0x16121b0, 0x15fe080)         E:/Project/go_update/src/handler.go:721 +0xd5c net/http.HandlerFunc.ServeHTTP(0x3d37f8, 0x446e08, 0x16121b0, 0x15fe080)         D:/Go/src/net/http/server.go:2012 +0x34 net/http.(*ServeMux).ServeHTTP(0x68c470, 0x446e08, 0x16121b0, 0x15fe080)         D:/Go/src/net/http/server.go:2387 +0x16c net/http.serverHandler.ServeHTTP(0x14ae630, 0x446e08, 0x16121b0, 0x15fe080)         D:/Go/src/net/http/server.go:2807 +0x88 net/http.(*conn).serve(0x14c8480, 0x447568, 0x1604020)         D:/Go/src/net/http/server.go:1895 +0x7d4 created by net/http.(*Server).Serve         D:/Go/src/net/http/server.go:2933 +0x2d0

**Comment by ethsonliu** [comment]
得在 Run 里边加锁，我在外部加锁没用，哈哈哈哈。

嗯，希望后续改为线程安全，作者辛苦了。
