### ISSUE TITLE
为啥在Time结构体里边，把timeNode换一下位置，就不行了

### ISSUE THREAD

**Issue by Trickee** [antlabs/timer#5]
修改之前：
`
type Time struct {
	timeNode
	sync.Mutex

	// |---16bit---|---16bit---|------32bit-----|
	// |---level---|---index---|-------seq------|
	// level 在near盘子里就是1, 在T2ToTt[0]盘子里就是2起步
	// index 就是各自盘子的索引值
	// seq   自增id
	version uint64
}
`

修改之后：
`type Time struct {
	sync.Mutex

	// |---16bit---|---16bit---|------32bit-----|
	// |---level---|---index---|-------seq------|
	// level 在near盘子里就是1, 在T2ToTt[0]盘子里就是2起步
	// index 就是各自盘子的索引值
	// seq   自增id
	version uint64
	timeNode
}`

按代码来说，取的offsetof(Head)，调整一下位置应该是不影响的吧。
能否请教一下，谢谢！

**Comment by guonaihong** [comment]
如果说Offsetof是尺子, 可以量下这个成员变量到基址长度. 
```go
type A struct {
   X int32
   Y int32
}
```
Offsetof(y) 就是4.  那得到基地地址 =  y的地址-Offsetof(y) 

调整位置不会影响offsetof(Head)的计算, 但会影响遍历
![image](https://user-images.githubusercontent.com/5006959/142436197-9676f326-e0ed-4b9d-98aa-a20e40a96b4e.png)
你看到这个代码就知道, offset是相对Time结构体算出的. 但是链表的遍历却是timeNode. 根据上面的计算方面就知道, 如果类型不同的结构体, 如果list.Head前面插入元素, 那对Time.Head适合的offset对timeNode却是一个野指针的位置. 这也是我为什么要把timeNode放到第一个成员的原因, 哪怕这两个成员类型不一样, 对Time适用的offset对timeNode也是适用的.

**Comment by Trickee** [comment]
明白了，谢谢解答！

**Comment by guonaihong** [comment]
客气了. 那我先关闭这个issue
