### ISSUE TITLE
不定期打印Time has been called back错误

### ISSUE THREAD

**Issue by marsbible** [antlabs/timer#9]
请问如下的错误是何原因？有什么影响？谢谢

github.com/antlabs/timer:Time has been called back?from(165726941031)(165726941036)
github.com/antlabs/timer:Time has been called back?from(165726941031)(165726941036)
github.com/antlabs/timer:Time has been called back?from(165726941032)(165726941036)
github.com/antlabs/timer:Time has been called back?from(165726941032)(165726941036)
github.com/antlabs/timer:Time has been called back?from(165726941032)(165726941036)

**Comment by guonaihong** [comment]
机器的时间准吗?

**Comment by guonaihong** [comment]
可否发下用法的代码?

**Comment by marsbible** [comment]
> 可否发下用法的代码?

就是简单的使用，类似
if retryNext != time.Duration(0) {
    TM.AfterFunc(retryNext,  callback)
}

**Comment by marsbible** [comment]
最新版本暂未发现问题，先关闭了
